[project]
name = "cslbot-tjhsst"
version = "0.4"
license = "GPL-2.0-or-later"
readme = "README.rst"
description = "TJHSST-Specific modifications for cslbot."
authors = [
  {name = "The TJHSST Computer Systems Lab", email = "cslbot@pefoley.com"},
]
requires-python = ">=3.12"
dependencies = [
    "feedparser>=6.0.14",
    "tensorflow>=2.21.0"
]

[project.urls]
Repository = "https://github.com/tjcsl/cslbot-tjhsst"

[tool.poetry]
packages = [
  { include = "cslbot-tjhsst" },
]

[tool.poetry.dependencies]
tensorflow = {allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
